### ISSUE TITLE
Pickle format python 2 & 3

### ISSUE THREAD

**Issue by mattbierbaum** [peri-source/peri#2]
When using Python 2.7 and 3.x on the same machine with PERI, conflicts develop between the generation of pickle files, particularly the wisdom file. The default protocol for 3.x is 4, while I believe it is 0 for 2.7 (regardless, 2.7 cannot read protocol 4). Should we just standardize to protocol 2 for pickle since it is 'good enough'? Tagging @briandleahy

**Comment by briandleahy** [comment]
I'm assuming that you've already browsed the interwebs for thoughts. 

It seems that protocol 2 is the one that works for Py2, no?
http://stackoverflow.com/questions/25843698/valueerror-unsupported-pickle-protocol-3-python2-pickle-can-not-load-the-file
http://stackoverflow.com/questions/29587179/load-pickle-filecomes-from-python3-in-python2

But I agree -- it seems that setting  the protocol to a fixed number like 2 is good enough.

**Comment by mattbierbaum** [comment]
Okay, updated with 7b3e380

**Comment by briandleahy** [comment]
Uh, this is the wrong hash. I believe it should be 7e988bc
