### ISSUE TITLE
Problems with installing peri on Mac OS High Sierra

### ISSUE THREAD

**Issue by mingxiao2017** [peri-source/peri#6]
I used Python 3.6 and when I tried to install peri on Mac OS High Sierra. It failed and required me to install pyfftw. I tried to install pyfftw and it failed too. When I switched to Python 2.7 environment, I had no problem installing pyfftw.

**Comment by mattbierbaum** [comment]
Can you provide more details? What actions did you take (command line entries) and what error messages or logs did you receive? Thanks!

**Comment by briandleahy** [comment]
This should be fixed on develop and master with commit 2b2113944d0c998662c245cc89adfe8984a84c53
